spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/betolyn
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: "create-only"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

services:
  redis:
    host: "localhost"
    port: 6379

app:
  auth:
    sessionExpirationInDays: 7
    cookiesTokenNameKey: "token"
    jwtSecret: "jS7I27ggI1XJMvxIPdylTRcB2g1zeeNY9jaBo0QeaQT"
